# Cloud Build for Cloud Scheduler Jobs Deployment (no $ variables, fully inline)
steps:
  # 1️⃣ Enable necessary APIs (hard-coded, no variables)
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'enable-apis-simple'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'gcloud services enable cloudscheduler.googleapis.com appengine.googleapis.com --quiet || echo "Some APIs may already be enabled"'

  # 2️⃣ Delete old Scheduler jobs
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'delete-01-min-job'
    args:
      - 'scheduler'
      - 'jobs'
      - 'delete'
      - '01-min-job'
      - '--location=asia-southeast1'
      - '--quiet'
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'delete-05-min-job'
    args:
      - 'scheduler'
      - 'jobs'
      - 'delete'
      - '05-min-job'
      - '--location=asia-southeast1'
      - '--quiet'
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'delete-15-min-job'
    args:
      - 'scheduler'
      - 'jobs'
      - 'delete'
      - '15-min-job'
      - '--location=asia-southeast1'
      - '--quiet'

  # 3️⃣ Create Scheduler jobs
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'create-sync-balance-job'
    args:
      - 'scheduler'
      - 'jobs'
      - 'create'
      - 'http'
      - '01-min-job'
      - '--location=asia-southeast1'
      - '--schedule=* * * * *'
      - '--uri=https://qrl-trading-api-545492969490.asia-southeast1.run.app/tasks/sync-balance'
      - '--http-method=POST'
      - '--headers=X-CloudScheduler=true'
      - '--headers=Content-Type=application/json'
      - '--message-body={}'
      - '--time-zone=Asia/Taipei'
      - '--description=Sync MEXC account balance to Redis every 1 minute'
      - '--attempt-deadline=60s'
      - '--max-retry-attempts=3'
      - '--min-backoff-duration=5s'
      - '--max-backoff-duration=60s'

  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'create-update-price-job'
    args:
      - 'scheduler'
      - 'jobs'
      - 'create'
      - 'http'
      - '05-min-job'
      - '--location=asia-southeast1'
      - '--schedule=*/5 * * * *'
      - '--uri=https://qrl-trading-api-545492969490.asia-southeast1.run.app/tasks/update-price'
      - '--http-method=POST'
      - '--headers=X-CloudScheduler=true'
      - '--headers=Content-Type=application/json'
      - '--message-body={}'
      - '--time-zone=Asia/Taipei'
      - '--description=Update QRL/USDT price from MEXC every 5 minutes'
      - '--attempt-deadline=60s'
      - '--max-retry-attempts=3'
      - '--min-backoff-duration=5s'
      - '--max-backoff-duration=60s'

  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'create-update-cost-job'
    args:
      - 'scheduler'
      - 'jobs'
      - 'create'
      - 'http'
      - '15-min-job'
      - '--location=asia-southeast1'
      - '--schedule=*/15 * * * *'
      - '--uri=https://qrl-trading-api-545492969490.asia-southeast1.run.app/tasks/update-cost'
      - '--http-method=POST'
      - '--headers=X-CloudScheduler=true'
      - '--headers=Content-Type=application/json'
      - '--message-body={}'
      - '--time-zone=Asia/Taipei'
      - '--description=Update cost and PnL calculations every 15 minutes'
      - '--attempt-deadline=60s'
      - '--max-retry-attempts=3'
      - '--min-backoff-duration=5s'
      - '--max-backoff-duration=60s'

  # 4️⃣ List jobs for verification
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'list-jobs'
    args:
      - 'scheduler'
      - 'jobs'
      - 'list'
      - '--location=asia-southeast1'

  # 5️⃣ Test trigger jobs
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'test-jobs'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'echo "Waiting a bit for Cloud Run to be ready..."; sleep 20; echo "Triggering scheduler jobs..."; gcloud scheduler jobs run 01-min-job --location=asia-southeast1 || true; sleep 3; gcloud scheduler jobs run 05-min-job --location=asia-southeast1 || true; sleep 3; gcloud scheduler jobs run 15-min-job --location=asia-southeast1 || true; echo "Test triggers finished."'

timeout: '900s'
options:
  logging: CLOUD_LOGGING_ONLY
